services:
  postgreSQL:
    image: postgres:16.4
    container_name: postgre_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ADMIN
      - POSTGRES_DB=phrases
    volumes:
      - ./postgres-data:/var/lib/postgresql/data